### ISSUE TITLE
Kmbox support?

### ISSUE THREAD

**Issue by OzymoGit** [Seconb/Aimmy-Arduino-Edition#10]
adruino and host shield required alot of tinkering.
At the same time kmbox almost plug and play.
Can you consider making it support kmbox natively?

**Comment by Seconb** [comment]
i don’t have a kmbox and don’t plan on buying one

host shield isn’t that hard to set up the problem is just that i also don’t have one of those nor do i plan on buying one. either way, even with the host shield it’s still detected on valorant

**Comment by OzymoGit** [comment]
> i don’t have a kmbox and don’t plan on buying one
> 
> host shield isn’t that hard to set up the problem is just that i also don’t have one of those nor do i plan on buying one. either way, even with the host shield it’s still detected on valorant

what if you only send left click ig trigger bot only? with valorant still ban you?

**Comment by Seconb** [comment]
> > i don’t have a kmbox and don’t plan on buying one
> > host shield isn’t that hard to set up the problem is just that i also don’t have one of those nor do i plan on buying one. either way, even with the host shield it’s still detected on valorant
> 
> what if you only send left click ig trigger bot only? with valorant still ban you?

they will ban if i send a left click but if you make a trigger bot that presses a key on your keyboard, then set your 2nd shooting bind to that key it’ll work undetected

**Comment by OzymoGit** [comment]
> > > i don’t have a kmbox and don’t plan on buying one
> > > host shield isn’t that hard to set up the problem is just that i also don’t have one of those nor do i plan on buying one. either way, even with the host shield it’s still detected on valorant
> > 
> > 
> > what if you only send left click ig trigger bot only? with valorant still ban you?
> 
> they will ban if i send a left click but if you make a trigger bot that presses a key on your keyboard, then set your 2nd shooting bind to that key it’ll work undetected

thanks for the info, didnt know you can do that, cheer

**Comment by OzymoGit** [comment]
@Seconb sorry for bother you again but 2 have somes questions.
1. When I plug my mouse in to Andruino + host shield. If I click the mouse the andruino send left click event, it is OK. But the when the cheat send left click, it detected, why? aren't they the same after goes through andruino?
2. What if I send Key press and get flag too like the problem above?.
Sorr

**Comment by Seconb** [comment]
using the keyboard to send input is undetected because vanguard cant check for it.

if you use the mouse to send click in your script it sets win32 flag, vanguard checks it and you get banned

arduino acts like a real mouse and sends left click like a normal mouse but riot detects the arduino connected to your pc or the com port. (this uses HID but i think thats detected too)

**Comment by OzymoGit** [comment]
So I just plug the arduino in and then send key press. I can have two keyboard at the same time and vanguard ok with that?.
wow

**Comment by Seconb** [comment]
you dont need an arduino to send keypress lol

you only need an arduino if you want to move the mouse like aimbot

**Comment by OzymoGit** [comment]
is it possible to run visual detection on another pc in the same local net and send keyboard. press over ?

**Comment by Seconb** [comment]
> is it possible to run visual detection on another pc in the same local net and send keyboard. press over ?

i guess theres a way but why would you want to do that when you dont have to?

this method of using keyboard has been undetected for years, riot has known about it since forever
