### ISSUE TITLE
Absolutemouse not detected

### ISSUE THREAD

**Issue by 1337sense** [Seconb/Aimmy-Arduino-Edition#13]
In file included from C:\Users\Admin\Downloads\Aimmy.Arduino.Edition.v3.1\Aimmy Arduino Edition v3.1\MouseInstructArduino\MouseInstructArduino.ino:3:0:
ImprovedMouse.h:3:10: fatal error: AbsoluteMouse.h: No such file or directory
 #include "AbsoluteMouse.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
AbsoluteMouse.h: No such file or directory

**Comment by Seconb** [comment]
download the oldest version of arduino aimmy and replace the mouseinstruct arduino files for the new one with the ones from the old one.

you also need to press ctrl+shift+i while in the arduino IDE, search for HID-Project, and install that then try again
