### ISSUE TITLE
KMBOX support

### ISSUE THREAD

**Issue by Roy992** [Seconb/Aimmy-Arduino-Edition#15]
Bro. It is amazing that you made for arduino. This can use KMBoX b also ?  I hope you can made for KMBoX also. Thank you ☺️

**Comment by Seconb** [comment]
no fuck off

**Comment by Roy992** [comment]
Why so angry? 🙄

**Comment by Seconb** [comment]
> Why so angry? 🙄

because instead of actually trying to make something yourself youre begging me to do all the hard work for you

fuck off. you dont just buy a kmbox to use free cheats, you use it to make something yourself because not many people make kmbox cheats

**Comment by Roy992** [comment]
I don’t know anything about programming. I just heard from some group that KMBoX is like Arduino. So I thought can use and easy for you to put since you are prog. Sry. If look like it is hard. Just ignore my msg. Thx

**Comment by Seconb** [comment]
"I don’t know anything about programming"

That says everything
