### ISSUE TITLE
Restore COM Port

### ISSUE THREAD

**Issue by mortezaghafoori** [Seconb/Aimmy-Arduino-Edition#19]
Ho do I restore the removed COM Port so I can use it again? (Reprogram the Arduino to something else)

**Comment by Seconb** [comment]
unspoof using the spoofer then upload any script to your arduino, making sure to press reset a few seconds after clicking the upload button

**Comment by mortezaghafoori** [comment]
I tried that but apparently the modified usbcore.cpp had a problem and the COM port didn't come back. So I had to reinstall Arduino IDE and upload a script again to restore everything back to normal

**Comment by Seconb** [comment]
> I tried that but apparently the modified usbcore.cpp had a problem and the COM port didn't come back. So I had to reinstall Arduino IDE and upload a script again to restore everything back to normal

it would’ve helped for you to tell me you had the modified usbcore, the modded usb core permanently disables the com port so u have to keep the old usbcore on ur pc just in case
