### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by goxdev7** [Seconb/Aimmy-Arduino-Edition#22]
how do i connect my ardunio to my pc if i don't have usb host shield

**Comment by goxdev7** [comment]
ok solved lol

**Comment by WenRou-Pan** [comment]
> ok solved lol

How did you solve it? Discuss it.

**Comment by Seconb** [comment]
> > ok solved lol
> 
> How did you solve it? Discuss it.

read the github page you CANT use a usb host shield
just plug in the arduino and mouse separately
you cant use this on valorant or faceit anyway so it doesnt matter
also doesnt work on fortnite, basically every other game imaginable is fine prob
