### ISSUE TITLE
Labeling using trained model

### ISSUE THREAD

**Issue by mortezaghafoori** [Seconb/Aimmy-Arduino-Edition#26]
Is there anyway to convert my trained model into a format where I can use it it makesense . ai so the automatic detection gets better every time I train my model on more pictures? I don't know if this is possible or not but it would be very awesome to be able to do that. Thanks!

**Comment by Seconb** [comment]
this issue should go to normal aimmy, join their discord and ask there

im pretty sure what ur asking is impossible but dont followup here just go ask on aimmy discord
