### ISSUE TITLE
No mouse device found.

### ISSUE THREAD

**Issue by Revertings** [Seconb/Aimmy-Arduino-Edition#5]
Only issue I could find (done everything right) is it has something to do with my usb host shield (I was using usb host shield and then took it out for anytime I used aimmy) thats when it stopped working. 
![image](https://github.com/Seconb/Aimmy-Arduino-Edition/assets/165695909/6fc93554-8e05-4077-9e65-5fd2d25858a7)

**Comment by Revertings** [comment]
I also would like to say I know my other things sound formal and rude but genuinely I love what your doing. The mouse movement source has helped me learn to actually code something to start off for a colorbot I'm trying to make, much love.

**Comment by Revertings** [comment]
Downloaded the new version and ran that new .ino file. Issue fixed? (somehow I have no clue) I uploaded the old .ino when I was troubleshooting, no clue how this worked.

**Comment by Seconb** [comment]
it seems your issue had something to do with the HID-Project library that i used to communicate with the arduino, all i did was package it with the .ino file so u dont have to go and download it yourself from the arduino menu

**Comment by Revertings** [comment]
When I changed scripts to fit my usb host shield it installed a different version of the HID project library, that could be the issue?

**Comment by Seconb** [comment]
did you get it to work with the host shield?
