### ISSUE TITLE
HID-Settings.h: No such file or directory  #include "HID-Settings.h"

### ISSUE THREAD

**Issue by Lozarth** [Seconb/Aimmy-Arduino-Edition#7]
In file included from C:\Users\monko\Downloads\Aimmy.Arduino.Edition.v3\Aimmy Arduino Edition v3\MouseInstructArduino\HID-Project.h:39:0,
                 from C:\Users\monko\Downloads\Aimmy.Arduino.Edition.v3\Aimmy Arduino Edition v3\MouseInstructArduino\MouseInstructArduino.ino:1:
C:\Users\monko\Downloads\Aimmy.Arduino.Edition.v3\Aimmy Arduino Edition v3\MouseInstructArduino\SingleReport\SingleAbsoluteMouse.h:29:10: fatal error: HID-Settings.h: No such file or directory
 #include "HID-Settings.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Leonardo.

**Comment by Seconb** [comment]
attempt to use the mouseinstructarduino files from this download:

https://github.com/Seconb/Aimmy-Arduino-Edition/releases/download/v1/Aimmy.Arduino.v2.1.rar

if it works let me know

**Comment by Lozarth** [comment]
> attempt to use the mouseinstructarduino files from this download:
> 
> https://github.com/Seconb/Aimmy-Arduino-Edition/releases/download/v1/Aimmy.Arduino.v2.1.rar
> 
> if it works let me know

Same error

**Comment by Seconb** [comment]
> > attempt to use the mouseinstructarduino files from this download:
> > https://github.com/Seconb/Aimmy-Arduino-Edition/releases/download/v1/Aimmy.Arduino.v2.1.rar
> > if it works let me know
> 
> Same error

press ctrl+shift+i with mouseinstructarduino.ino open, then search HID-Project and install it then try again

**Comment by Lozarth** [comment]
> > > attempt to use the mouseinstructarduino files from this download:
> > > https://github.com/Seconb/Aimmy-Arduino-Edition/releases/download/v1/Aimmy.Arduino.v2.1.rar
> > > if it works let me know
> > 
> > 
> > Same error
> 
> press ctrl+shift+i with mouseinstructarduino.ino open, then search HID-Project and install it then try again

That worked thanks
